# create a docker-compose.yml file
version: "2.1"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db